version: 2
updates:
  - package-ecosystem: "gomod"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(go-deps):"
    labels:
      - "dependencies"
      - "go"
    ignore:
      - dependency-name: "go"
    target-branch: "master"
    groups:
      all-go-deps:
        patterns:
          - "*"
