name: CI

on:
  pull_request:
    branches: 
      - master
      - main
    paths-ignore: 
      - ".github/workflows/release.yml"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends binfmt-support qemu-user-static
      - run: ./build.sh
      - run: ./test.sh gosu-amd64
      - run: ./test.sh gosu-i386
      - run: ./test.sh --debian gosu-amd64
      - run: ./test.sh --debian gosu-i386
      - run: docker build --pull --file hub/Dockerfile.alpine hub
      - run: docker build --pull --file hub/Dockerfile.debian hub

      - name: govulncheck
        run: |
          for gosu in gosu-*; do
            ./govulncheck-with-excludes.sh -mode=binary "$gosu"
          done
